"""Internal latexdiff generation, marked compilation, and temporary locations."""

from __future__ import annotations

import collections
import re
import shutil
from dataclasses import dataclass
from itertools import pairwise
from pathlib import Path

from .compile import compile_tex, run_command, stage_runtime_resources
from .response import is_review_id
from .workspace import ProjectConfig, WorkflowError, strip_provenance_wrappers

INPUT_PATTERN = re.compile(r"\\(?:input|include)\s*\{([^}]+)\}")
LABEL_PATTERN = re.compile(r"\\newlabel\{review:(\d+):(start|end)\}\{\{(\d+)\}")
REVIEW_REGISTRY_HEADER = "sci-manuscript-reviewloc-v1"
INTERNAL_REVIEW_START = r"\sciReviewStart"
INTERNAL_REVIEW_END = r"\sciReviewEnd"
CHINESE_TEXT_COMMANDS = (
    "cnabstract",
    "cnkeywords",
    "enabstract",
    "enkeywords",
    "firstauthorcn",
    "firstauthoren",
    "funding",
    "entitle",
)

# Zero-width token used only while diffing CJK prose. It is removed before
# the marked source is compiled, so it cannot alter manuscript rendering.
CJK_DIFF_BOUNDARY = "\u200b"

_REVISION_RUNTIME_TEMPLATE = r"""
% Internal latexdiff and reviewer-location runtime. Generated by the workflow.
\RequirePackage{lineno}
\RequirePackage[normalem]{ulem}
%%CJK_REVISION_PACKAGE%%
\RequirePackage{xcolor}
\AtBeginDocument{\linenumbers}

% Automatic diffs can contain arbitrary LaTeX: CJK paragraphs, mathematics,
% citations, headings, lists, and floats.  Structural provenance wrappers stay
% transparent; text-level latexdiff spans receive the agreed line decoration.
% Mathematics is split out before compilation and remains color-only because
% ulem/xeCJKfntef scanners cannot safely consume arbitrary math material.
\providecommand{\DIFaddMath}[1]{%
  {\RevisionAddedFont\color{RevisionAddedColor}#1}%
}
\providecommand{\DIFaddReviewMath}[1]{%
  {\RevisionReviewFont\color{RevisionReviewColor}#1}%
}
\newbox\DIFdelDisplayMathBox
\providecommand{\DIFdelMath}[1]{%
  \ifmmode
    % A display formula is already an atomic horizontal math object. Measure it
    % once, reuse the exact box, and overlay a zero-width strike at its visual
    % centre. The overlay neither widens the formula nor feeds math to ulem.
    \begingroup
      \setbox\DIFdelDisplayMathBox=\hbox{$\displaystyle\RevisionDeletedFont
        \color{RevisionDeletedColor}#1$}%
      \dimen0=.5\ht\DIFdelDisplayMathBox
      \advance\dimen0 by -.5\dp\DIFdelDisplayMathBox
      \rlap{\raise\dimen0\hbox{\color{RevisionDeletedColor}%
        \rule{\wd\DIFdelDisplayMathBox}{0.6pt}}}%
      \box\DIFdelDisplayMathBox
    \endgroup
  \else
    \begingroup
      \setbox\DIFdelDisplayMathBox=\hbox{{\RevisionDeletedFont
        \color{RevisionDeletedColor}#1}}%
      \dimen0=.5\ht\DIFdelDisplayMathBox
      \advance\dimen0 by -.5\dp\DIFdelDisplayMathBox
      \rlap{\raise\dimen0\hbox{\color{RevisionDeletedColor}%
        \rule{\wd\DIFdelDisplayMathBox}{0.6pt}}}%
      \box\DIFdelDisplayMathBox
    \endgroup
  \fi}
\providecommand{\DIFadd}[1]{%
  \ifmmode
    \DIFaddMath{#1}%
  \else
    \RevisionAddedBackground{{\RevisionAddedFont\color{RevisionAddedColor}\RevisionAddedUnderline{#1}}}%
  \fi
}
\providecommand{\DIFaddReview}[1]{%
  \ifmmode
    \DIFaddReviewMath{#1}%
  \else
    \RevisionReviewBackground{{\RevisionReviewFont\color{RevisionReviewColor}\RevisionReviewUnderline{#1}}}%
  \fi
}
\providecommand{\DIFdel}[1]{%
  \ifmmode
    \DIFdelMath{#1}%
  \else
    \RevisionDeletedBackground{{\RevisionDeletedFont\color{RevisionDeletedColor}\RevisionDeletedStrikeout{#1}}}%
  \fi}
\providecommand{\DIFaddbegin}{}
\providecommand{\DIFaddend}{}
\providecommand{\DIFdelbegin}{}
\providecommand{\DIFdelend}{}
\providecommand{\DIFmodbegin}{}
\providecommand{\DIFmodend}{}
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}}
\providecommand{\DIFaddReviewFL}[1]{\DIFaddReview{#1}}
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}}
\providecommand{\DIFaddbeginFL}{}
\providecommand{\DIFaddendFL}{}
\providecommand{\DIFdelbeginFL}{}
\providecommand{\DIFdelendFL}{}

\newcounter{reviewblock}
\newwrite\ReviewLocationFile
\AtBeginDocument{%
  \immediate\openout\ReviewLocationFile=\jobname.reviewloc
  \immediate\write\ReviewLocationFile{%%REVIEW_REGISTRY_HEADER%%}%
}
\AtEndDocument{\immediate\closeout\ReviewLocationFile}

\newcommand{\ReviewLineLabel}[1]{%
  \begingroup
  \edef\ReviewExpandedLabel{#1}%
  \expandafter\endgroup
  \expandafter\linelabel\expandafter{\ReviewExpandedLabel}%
}

\providecommand{\review}[2]{#2}
\providecommand{\user}[1]{#1}
\providecommand{\sciReviewStart}[1]{}
\providecommand{\sciReviewEnd}[1]{}
\newcommand{\CurrentReviewBlockID}{0}
\AtBeginDocument{%
  % User-facing provenance wrappers stay visually transparent. The marked-source
  % preprocessor replaces \review with internal boundaries before latexdiff so
  % unchanged text can still align with the parent revision.
  \renewcommand{\review}[2]{#2}%
  \renewcommand{\user}[1]{#1}%
  \renewcommand{\sciReviewStart}[1]{%
    \stepcounter{reviewblock}%
    \xdef\CurrentReviewBlockID{\arabic{reviewblock}}%
    \leavevmode
    \ReviewLineLabel{review:\CurrentReviewBlockID:start}%
    \immediate\write\ReviewLocationFile{#1|\CurrentReviewBlockID}%
  }%
  \renewcommand{\sciReviewEnd}[1]{%
    \leavevmode
    \ReviewLineLabel{review:\CurrentReviewBlockID:end}%
  }%
}
"""
REVISION_RUNTIME = _REVISION_RUNTIME_TEMPLATE.replace(
    "%%REVIEW_REGISTRY_HEADER%%", REVIEW_REGISTRY_HEADER
).replace("%%CJK_REVISION_PACKAGE%%", "")


def _revision_runtime(language: str) -> str:
    cjk_package = r"\RequirePackage{xeCJKfntef}" if language == "zh" else ""
    return _REVISION_RUNTIME_TEMPLATE.replace(
        "%%REVIEW_REGISTRY_HEADER%%", REVIEW_REGISTRY_HEADER
    ).replace("%%CJK_REVISION_PACKAGE%%", cjk_package)


@dataclass(frozen=True)
class MarkedResult:
    """Published marked PDF and in-memory reviewer locations."""

    pdf: Path
    locations: dict[str, str]


def _flatten_tex(
    path: Path,
    roots: tuple[Path, ...],
    active: tuple[Path, ...] = (),
) -> str:
    """Expand manuscript and shared-reference inputs for deterministic diffing."""
    resolved = path.resolve()
    if resolved in active:
        chain = " -> ".join(item.name for item in (*active, resolved))
        raise WorkflowError(f"Recursive TeX input detected: {chain}")
    if not any(resolved.is_relative_to(root.resolve()) for root in roots):
        raise WorkflowError(f"TeX input escapes permitted project roots: {resolved}")
    text = resolved.read_text(encoding="utf-8")

    def replace_input(match: re.Match[str]) -> str:
        name = match.group(1).strip()
        candidate = resolved.parent / name
        if candidate.suffix == "":
            candidate = candidate.with_suffix(".tex")
        if not candidate.exists():
            for root in roots:
                alternate = root / name
                if alternate.suffix == "":
                    alternate = alternate.with_suffix(".tex")
                if alternate.exists():
                    candidate = alternate
                    break
        if not candidate.exists():
            return match.group(0)
        nested = _flatten_tex(candidate, roots, (*active, resolved))
        return f"\n% BEGIN INPUT {name}\n{nested}\n% END INPUT {name}\n"

    return INPUT_PATTERN.sub(replace_input, text)


def _copy_resources(config: ProjectConfig, round_dir: Path, target: Path) -> None:
    stage_runtime_resources(
        config,
        config.current_round,
        target,
        include_manuscript=False,
    )


def _is_escaped(text: str, index: int) -> bool:
    count = 0
    cursor = index - 1
    while cursor >= 0 and text[cursor] == "\\":
        count += 1
        cursor -= 1
    return count % 2 == 1


def _is_cjk_diff_char(char: str) -> bool:
    """Return whether one character should be isolated for CJK text diffing."""
    codepoint = ord(char)
    return (
        0x3400 <= codepoint <= 0x4DBF
        or 0x4E00 <= codepoint <= 0x9FFF
        or 0xF900 <= codepoint <= 0xFAFF
        or 0x20000 <= codepoint <= 0x2FA1F
        or 0x3000 <= codepoint <= 0x303F
        or 0xFF00 <= codepoint <= 0xFFEF
    )


def _tokenize_cjk_for_diff(text: str) -> str:
    """Insert removable zero-width boundaries so latexdiff can align CJK text."""
    if not text:
        return text
    tex_structure = set("{}\\$%&#_^~")
    output = [text[0]]
    for previous, current in pairwise(text):
        if (
            not previous.isspace()
            and not current.isspace()
            and previous not in tex_structure
            and current not in tex_structure
            and (_is_cjk_diff_char(previous) or _is_cjk_diff_char(current))
        ):
            output.append(CJK_DIFF_BOUNDARY)
        output.append(current)
    return "".join(output)


def _remove_cjk_diff_boundaries(text: str) -> str:
    """Remove every temporary CJK diff boundary before marked compilation."""
    return text.replace(CJK_DIFF_BOUNDARY, "")


def _extract_braced(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise WorkflowError("Internal parser expected an opening brace.")
    depth = 0
    cursor = start
    while cursor < len(text):
        char = text[cursor]
        if char == "%" and not _is_escaped(text, cursor):
            newline = text.find("\n", cursor)
            cursor = len(text) if newline == -1 else newline + 1
            continue
        if char == "{" and not _is_escaped(text, cursor):
            depth += 1
        elif char == "}" and not _is_escaped(text, cursor):
            depth -= 1
            if depth == 0:
                return text[start + 1 : cursor], cursor + 1
        cursor += 1
    raise WorkflowError("Unbalanced braces while processing latexdiff output.")


def _skip_space(text: str, start: int) -> int:
    cursor = start
    while cursor < len(text) and text[cursor].isspace():
        cursor += 1
    return cursor


def _parse_command_arguments(
    text: str,
    start: int,
    name: str,
    count: int,
) -> tuple[tuple[str, ...], int] | None:
    if not text.startswith(name, start):
        return None
    end_name = start + len(name)
    if end_name < len(text) and (text[end_name].isalnum() or text[end_name] == "@"):
        return None
    cursor = end_name
    arguments: list[str] = []
    for _ in range(count):
        cursor = _skip_space(text, cursor)
        if cursor >= len(text) or text[cursor] != "{":
            return None
        argument, cursor = _extract_braced(text, cursor)
        arguments.append(argument)
    return tuple(arguments), cursor


def _expand_provenance_wrappers(text: str, *, review_depth: int = 0) -> str:
    """Replace user provenance wrappers with transparent diff boundaries."""
    output: list[str] = []
    cursor = 0
    while cursor < len(text):
        if text[cursor] == "%" and not _is_escaped(text, cursor):
            newline = text.find("\n", cursor)
            end = len(text) if newline == -1 else newline + 1
            output.append(text[cursor:end])
            cursor = end
            continue
        if text[cursor] == "\\":
            parsed_review = _parse_command_arguments(text, cursor, r"\review", 2)
            if parsed_review is not None:
                if review_depth:
                    raise WorkflowError(
                        "Nested \\review blocks are ambiguous; combine reviewer IDs "
                        "in one wrapper instead."
                    )
                (raw_ids, body), end = parsed_review
                review_ids = tuple(
                    item.strip() for item in raw_ids.split(",") if item.strip()
                )
                if not review_ids or any(not is_review_id(item) for item in review_ids):
                    raise WorkflowError(
                        f"Invalid reviewer ID list {raw_ids!r}; expected IDs such as 1-1."
                    )
                ids = ",".join(review_ids)
                expanded_body = _expand_provenance_wrappers(body, review_depth=1)
                output.append(
                    f"{INTERNAL_REVIEW_START}{{{ids}}}{expanded_body}"
                    f"{INTERNAL_REVIEW_END}{{{ids}}}"
                )
                cursor = end
                continue
            parsed_user = _parse_command_arguments(text, cursor, r"\user", 1)
            if parsed_user is not None:
                (body,), end = parsed_user
                output.append(
                    _expand_provenance_wrappers(body, review_depth=review_depth)
                )
                cursor = end
                continue
        output.append(text[cursor])
        cursor += 1
    return "".join(output)


def _parse_provenance_command(text: str, start: int) -> tuple[str, int] | None:
    for name, count in (
        (INTERNAL_REVIEW_START, 1),
        (INTERNAL_REVIEW_END, 1),
        (r"\review", 2),
        (r"\user", 1),
    ):
        parsed = _parse_command_arguments(text, start, name, count)
        if parsed is not None:
            _, end = parsed
            return text[start:end], end
    return None


def _split_added_content(content: str, macro: str) -> str:
    pieces: list[str] = []
    regular_start = 0
    cursor = 0
    depth = 0
    found = False
    while cursor < len(content):
        char = content[cursor]
        if char == "%" and not _is_escaped(content, cursor):
            newline = content.find("\n", cursor)
            cursor = len(content) if newline == -1 else newline + 1
            continue
        if char == "{" and not _is_escaped(content, cursor):
            depth += 1
            cursor += 1
            continue
        if char == "}" and not _is_escaped(content, cursor):
            depth = max(0, depth - 1)
            cursor += 1
            continue
        if depth == 0 and char == "\\":
            parsed = _parse_provenance_command(content, cursor)
            if parsed is not None:
                special, end = parsed
                ordinary = content[regular_start:cursor]
                if ordinary:
                    pieces.append(
                        ordinary if ordinary.isspace() else f"{macro}{{{ordinary}}}"
                    )
                pieces.append(special)
                found = True
                cursor = end
                regular_start = end
                continue
        cursor += 1
    if not found:
        return f"{macro}{{{content}}}"
    ordinary = content[regular_start:]
    if ordinary:
        pieces.append(ordinary if ordinary.isspace() else f"{macro}{{{ordinary}}}")
    return "".join(pieces)


def _denest_provenance(text: str) -> str:
    macros = (r"\DIFaddFL", r"\DIFadd")
    output: list[str] = []
    cursor = 0
    while cursor < len(text):
        candidates = [(text.find(f"{macro}{{", cursor), macro) for macro in macros]
        matches = [item for item in candidates if item[0] != -1]
        if not matches:
            output.append(text[cursor:])
            break
        index, macro = min(matches, key=lambda item: item[0])
        output.append(text[cursor:index])
        content, end = _extract_braced(text, index + len(macro))
        output.append(_split_added_content(content, macro))
        cursor = end
    result = "".join(output)
    for macro in macros:
        cursor = 0
        while True:
            index = result.find(f"{macro}{{", cursor)
            if index < 0:
                break
            content, end = _extract_braced(result, index + len(macro))
            if any(
                marker in content
                for marker in (
                    INTERNAL_REVIEW_START,
                    INTERNAL_REVIEW_END,
                    r"\review",
                    r"\user",
                )
            ):
                raise WorkflowError(
                    "Could not safely separate provenance markup from latexdiff output."
                )
            cursor = end
    return result


def _mark_reviewer_additions(text: str) -> str:
    """Classify only latexdiff additions inside review boundaries as reviewer work."""
    output: list[str] = []
    cursor = 0
    active_ids: str | None = None
    while cursor < len(text):
        if text[cursor] == "%" and not _is_escaped(text, cursor):
            newline = text.find("\n", cursor)
            end = len(text) if newline == -1 else newline + 1
            output.append(text[cursor:end])
            cursor = end
            continue
        if text[cursor] == "\\":
            start_marker = _parse_command_arguments(
                text, cursor, INTERNAL_REVIEW_START, 1
            )
            if start_marker is not None:
                (ids,), end = start_marker
                if active_ids is not None:
                    raise WorkflowError(
                        "Nested internal reviewer boundaries are invalid."
                    )
                active_ids = ids
                output.append(text[cursor:end])
                cursor = end
                continue
            end_marker = _parse_command_arguments(text, cursor, INTERNAL_REVIEW_END, 1)
            if end_marker is not None:
                (ids,), end = end_marker
                if active_ids is None or ids != active_ids:
                    raise WorkflowError("Unbalanced internal reviewer boundaries.")
                active_ids = None
                output.append(text[cursor:end])
                cursor = end
                continue
            if active_ids is not None:
                for source, target in (
                    (r"\DIFaddFL", r"\DIFaddReviewFL"),
                    (r"\DIFadd", r"\DIFaddReview"),
                ):
                    parsed = _parse_command_arguments(text, cursor, source, 1)
                    if parsed is None:
                        continue
                    (content,), end = parsed
                    output.append(f"{target}{{{content}}}")
                    cursor = end
                    break
                else:
                    output.append(text[cursor])
                    cursor += 1
                continue
        output.append(text[cursor])
        cursor += 1
    if active_ids is not None:
        raise WorkflowError("Unclosed internal reviewer boundary in marked source.")
    return "".join(output)


def _find_inline_math_end(text: str, start: int) -> int | None:
    """Return the exclusive end of one inline-math span starting at *start*."""
    if text.startswith("$$", start):
        delimiter = "$$"
        cursor = start + 2
    elif text[start] == "$":
        delimiter = "$"
        cursor = start + 1
    elif text.startswith(r"\(", start):
        delimiter = r"\)"
        cursor = start + 2
    else:
        return None
    while cursor < len(text):
        if text.startswith(delimiter, cursor) and not _is_escaped(text, cursor):
            return cursor + len(delimiter)
        cursor += 1
    raise WorkflowError("Unbalanced inline mathematics in latexdiff markup.")


def _split_inline_math(content: str, macro: str) -> str:
    """Keep line decoration on text while moving inline math to color-only spans."""
    math_macros = {
        r"\DIFadd": r"\DIFaddMath",
        r"\DIFaddReview": r"\DIFaddReviewMath",
        r"\DIFdel": r"\DIFdelMath",
    }
    math_macro = math_macros[macro]
    pieces: list[str] = []
    plain_start = 0
    cursor = 0
    found = False
    while cursor < len(content):
        if content[cursor] == "%" and not _is_escaped(content, cursor):
            newline = content.find("\n", cursor)
            cursor = len(content) if newline == -1 else newline + 1
            continue
        is_math = (
            content[cursor] == "$" and not _is_escaped(content, cursor)
        ) or content.startswith(r"\(", cursor)
        if not is_math:
            cursor += 1
            continue
        end = _find_inline_math_end(content, cursor)
        if end is None:
            cursor += 1
            continue
        plain = content[plain_start:cursor]
        if plain:
            pieces.append(plain if plain.isspace() else f"{macro}{{{plain}}}")
        pieces.append(f"{math_macro}{{{content[cursor:end]}}}")
        cursor = end
        plain_start = end
        found = True
    if not found:
        return f"{macro}{{{content}}}"
    plain = content[plain_start:]
    if plain:
        pieces.append(plain if plain.isspace() else f"{macro}{{{plain}}}")
    return "".join(pieces)


def _separate_inline_math_from_diff_markup(text: str) -> str:
    """Rewrite inline math nested in text markup before line decoration scans it."""
    macros = (r"\DIFaddReview", r"\DIFadd", r"\DIFdel")
    output: list[str] = []
    cursor = 0
    while cursor < len(text):
        candidates = [(text.find(f"{macro}{{", cursor), macro) for macro in macros]
        matches = [item for item in candidates if item[0] != -1]
        if not matches:
            output.append(text[cursor:])
            break
        index, macro = min(matches, key=lambda item: item[0])
        output.append(text[cursor:index])
        content, end = _extract_braced(text, index + len(macro))
        output.append(_split_inline_math(content, macro))
        cursor = end
    return "".join(output)


def _parse_registry(path: Path) -> list[tuple[str, int]]:
    if not path.exists():
        raise WorkflowError(f"Marked build did not create a review registry: {path}")
    records: list[tuple[str, int]] = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or (number == 1 and line == REVIEW_REGISTRY_HEADER):
            continue
        fields = line.split("|")
        if len(fields) != 2 or not fields[1].isdigit():
            raise WorkflowError(f"Malformed review registry at line {number}: {raw}")
        records.append((fields[0], int(fields[1])))
    return records


def _parse_labels(path: Path) -> dict[tuple[int, str], int]:
    if not path.exists():
        raise WorkflowError(
            f"Marked build did not create a line-number AUX file: {path}"
        )
    labels: dict[tuple[int, str], int] = {}
    text = path.read_text(encoding="utf-8", errors="replace")
    for block, edge, line in LABEL_PATTERN.findall(text):
        labels[(int(block), edge)] = int(line)
    return labels


def _format_location(start: int, end: int) -> str:
    return f"Line {start}" if start == end else f"Lines {start}--{end}"


def _join_locations(locations: list[str]) -> str:
    if not locations:
        return "Location unavailable"
    if len(locations) == 1:
        return locations[0]
    if len(locations) == 2:
        return f"{locations[0]} and {locations[1]}"
    return f"{', '.join(locations[:-1])}, and {locations[-1]}"


def _calculate_locations(build_dir: Path) -> dict[str, str]:
    registry = _parse_registry(build_dir / "manuscript_marked.reviewloc")
    labels = _parse_labels(build_dir / "manuscript_marked.aux")
    by_comment: dict[str, list[str]] = collections.defaultdict(list)
    for ids, block in registry:
        start = labels.get((block, "start"))
        end = labels.get((block, "end"))
        if start is None or end is None:
            raise WorkflowError(f"Line labels are missing for reviewer block {block}.")
        location = _format_location(start, end)
        for review_id in (item.strip() for item in ids.split(",")):
            if not is_review_id(review_id):
                raise WorkflowError(
                    f"Invalid reviewer ID {review_id!r}; expected E-1 or 1-1."
                )
            if location not in by_comment[review_id]:
                by_comment[review_id].append(location)
    return {key: _join_locations(value) for key, value in by_comment.items()}


def build_marked_manuscript(
    config: ProjectConfig,
    round_number: int,
    run_dir: Path,
    engine_override: str | None = None,
) -> MarkedResult:
    """Build an R(N-1)-to-RN marked PDF and calculate temporary line locations."""
    if round_number < 1:
        raise WorkflowError("R0 has no marked manuscript; build its clean PDF instead.")
    previous = config.round_dir(round_number - 1)
    current = config.round_dir(round_number)
    if not previous.is_dir() or not current.is_dir():
        raise WorkflowError(
            f"Revision requires both r{round_number - 1} and r{round_number}."
        )
    if shutil.which("latexdiff") is None:
        raise WorkflowError("latexdiff is required for marked manuscripts.")
    if shutil.which("pdftotext") is None:
        raise WorkflowError("pdftotext is required for revision location extraction.")

    source_dir = run_dir / "marked_source"
    build_dir = run_dir / "marked_build"
    source_dir.mkdir(parents=True)
    roots = (previous, current, config.project)
    old_text = strip_provenance_wrappers(
        _flatten_tex(previous / "manuscript.tex", roots)
    )
    new_text = _expand_provenance_wrappers(
        _flatten_tex(current / "manuscript.tex", roots)
    )
    if config.language == "zh":
        old_text = _tokenize_cjk_for_diff(old_text)
        new_text = _tokenize_cjk_for_diff(new_text)
    old_source = source_dir / "old.tex"
    new_source = source_dir / "new.tex"
    old_source.write_text(old_text, encoding="utf-8")
    new_source.write_text(new_text, encoding="utf-8")
    style = source_dir / "revision_preamble.tex"
    user_style = (config.references / "revision_style.tex").read_text(encoding="utf-8")
    style.write_text(
        f"{user_style}\n{_revision_runtime(config.language)}", encoding="utf-8"
    )
    _copy_resources(config, current, source_dir)

    command = [
        shutil.which("latexdiff") or "latexdiff",
        "--encoding=utf8",
        "--packages=none",
        f"--preamble={style}",
        "--disable-citation-markup",
        "--ignore-warnings",
        str(old_source),
        str(new_source),
    ]
    if config.metadata.publisher == "chinese":
        command.insert(-3, f"--append-textcmd={','.join(CHINESE_TEXT_COMMANDS)}")
    result = run_command(command, cwd=source_dir)
    marked_source = source_dir / "manuscript_marked.tex"
    denested = _denest_provenance(result.stdout)
    if config.language == "zh":
        denested = _remove_cjk_diff_boundaries(denested)
    classified = _mark_reviewer_additions(denested)
    marked_source.write_text(
        _separate_inline_math_from_diff_markup(classified), encoding="utf-8"
    )
    compiled = compile_tex(
        marked_source,
        build_dir,
        config,
        engine_override,
        keep_intermediates=True,
    )
    extracted_text = run_dir / "marked_manuscript.txt"
    run_command(
        [
            shutil.which("pdftotext") or "pdftotext",
            str(compiled.pdf),
            str(extracted_text),
        ],
        cwd=run_dir,
    )
    if not extracted_text.exists() or extracted_text.stat().st_size == 0:
        raise WorkflowError("Marked PDF text extraction produced no text.")

    locations = _calculate_locations(build_dir)
    output = current / "output" / "manuscript_marked.pdf"
    output.parent.mkdir(exist_ok=True)
    shutil.copy2(compiled.pdf, output)
    return MarkedResult(pdf=output, locations=locations)
