"""Internal latexdiff generation, marked compilation, and temporary locations."""

from __future__ import annotations

import collections
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from compile import compile_tex, run_command
from workspace import ProjectConfig, WorkflowError, strip_provenance_wrappers

INPUT_PATTERN = re.compile(r"\\(?:input|include)\s*\{([^}]+)\}")
LABEL_PATTERN = re.compile(r"\\newlabel\{review:(\d+):(start|end)\}\{\{(\d+)\}")
REVIEW_ID = re.compile(r"^\d+-\d+$")

REVISION_RUNTIME = r"""
% Internal latexdiff and reviewer-location runtime. Generated by the workflow.
\RequirePackage{lineno}
\RequirePackage[normalem]{ulem}
\RequirePackage{xcolor}
\AtBeginDocument{\linenumbers}

\providecommand{\DIFadd}[1]{\RevisionAddedBackground{{\RevisionAddedFont\color{RevisionAddedColor}\RevisionAddedUnderline{#1}}}}
\providecommand{\DIFdel}[1]{\RevisionDeletedBackground{{\RevisionDeletedFont\color{RevisionDeletedColor}\RevisionDeletedStrikeout{#1}}}}
\providecommand{\DIFaddbegin}{}
\providecommand{\DIFaddend}{}
\providecommand{\DIFdelbegin}{}
\providecommand{\DIFdelend}{}
\providecommand{\DIFmodbegin}{}
\providecommand{\DIFmodend}{}
\providecommand{\DIFaddFL}[1]{\DIFadd{#1}}
\providecommand{\DIFdelFL}[1]{\DIFdel{#1}}
\providecommand{\DIFaddbeginFL}{}
\providecommand{\DIFaddendFL}{}
\providecommand{\DIFdelbeginFL}{}
\providecommand{\DIFdelendFL}{}

\newcounter{reviewblock}
\newwrite\ReviewLocationFile
\AtBeginDocument{\immediate\openout\ReviewLocationFile=\jobname.reviewloc}
\AtEndDocument{\immediate\closeout\ReviewLocationFile}

\newcommand{\ReviewLineLabel}[1]{%
  \begingroup
  \edef\ReviewExpandedLabel{#1}%
  \expandafter\endgroup
  \expandafter\linelabel\expandafter{\ReviewExpandedLabel}%
}

\providecommand{\review}[2]{#2}
\providecommand{\selfadd}[1]{#1}
\AtBeginDocument{%
  \renewcommand{\review}[2]{%
    \stepcounter{reviewblock}%
    \edef\ReviewBlockID{\arabic{reviewblock}}%
    \leavevmode
    \ReviewLineLabel{review:\ReviewBlockID:start}%
    \RevisionAddedBackground{{\RevisionAddedFont\color{RevisionAddedColor}\RevisionAddedUnderline{#2}}}%
    \ReviewLineLabel{review:\ReviewBlockID:end}%
    \immediate\write\ReviewLocationFile{#1|\ReviewBlockID}%
  }%
  \renewcommand{\selfadd}[1]{\RevisionSelfBackground{{\RevisionSelfFont\color{RevisionSelfColor}\RevisionSelfUnderline{#1}}}}%
}
"""


@dataclass(frozen=True)
class MarkedResult:
    """Published marked PDF and in-memory reviewer locations."""

    pdf: Path
    locations: dict[str, str]


def _flatten_tex(
    path: Path,
    roots: tuple[Path, ...],
    active: tuple[Path, ...] = (),
) -> str:
    """Expand manuscript and shared-reference inputs for deterministic diffing."""
    resolved = path.resolve()
    if resolved in active:
        chain = " -> ".join(item.name for item in (*active, resolved))
        raise WorkflowError(f"Recursive TeX input detected: {chain}")
    if not any(resolved.is_relative_to(root.resolve()) for root in roots):
        raise WorkflowError(f"TeX input escapes permitted project roots: {resolved}")
    text = resolved.read_text(encoding="utf-8")

    def replace_input(match: re.Match[str]) -> str:
        name = match.group(1).strip()
        candidate = resolved.parent / name
        if candidate.suffix == "":
            candidate = candidate.with_suffix(".tex")
        if not candidate.exists():
            for root in roots:
                alternate = root / name
                if alternate.suffix == "":
                    alternate = alternate.with_suffix(".tex")
                if alternate.exists():
                    candidate = alternate
                    break
        if not candidate.exists():
            return match.group(0)
        nested = _flatten_tex(candidate, roots, (*active, resolved))
        return f"\n% BEGIN INPUT {name}\n{nested}\n% END INPUT {name}\n"

    return INPUT_PATTERN.sub(replace_input, text)


def _copy_resources(config: ProjectConfig, round_dir: Path, target: Path) -> None:
    for directory in ("figures", "tables"):
        source = round_dir / directory
        if source.exists():
            shutil.copytree(source, target / directory, dirs_exist_ok=True)
    bibliography = config.references / "references.bib"
    if bibliography.exists():
        shutil.copy2(bibliography, target / "references.bib")
    publisher = config.references / "journal_template" / config.metadata.publisher
    if not publisher.is_dir():
        raise WorkflowError(f"Shared publisher template is missing: {publisher}")
    for resource in publisher.iterdir():
        if resource.is_file():
            shutil.copy2(resource, target / resource.name)


def _is_escaped(text: str, index: int) -> bool:
    count = 0
    cursor = index - 1
    while cursor >= 0 and text[cursor] == "\\":
        count += 1
        cursor -= 1
    return count % 2 == 1


def _extract_braced(text: str, start: int) -> tuple[str, int]:
    if start >= len(text) or text[start] != "{":
        raise WorkflowError("Internal parser expected an opening brace.")
    depth = 0
    cursor = start
    while cursor < len(text):
        char = text[cursor]
        if char == "%" and not _is_escaped(text, cursor):
            newline = text.find("\n", cursor)
            cursor = len(text) if newline == -1 else newline + 1
            continue
        if char == "{" and not _is_escaped(text, cursor):
            depth += 1
        elif char == "}" and not _is_escaped(text, cursor):
            depth -= 1
            if depth == 0:
                return text[start + 1 : cursor], cursor + 1
        cursor += 1
    raise WorkflowError("Unbalanced braces while processing latexdiff output.")


def _skip_space(text: str, start: int) -> int:
    cursor = start
    while cursor < len(text) and text[cursor].isspace():
        cursor += 1
    return cursor


def _parse_provenance_command(text: str, start: int) -> tuple[str, int] | None:
    for name, count in ((r"\review", 2), (r"\selfadd", 1)):
        if not text.startswith(name, start):
            continue
        end_name = start + len(name)
        if end_name < len(text) and (text[end_name].isalnum() or text[end_name] == "@"):
            continue
        cursor = end_name
        for _ in range(count):
            cursor = _skip_space(text, cursor)
            if cursor >= len(text) or text[cursor] != "{":
                return None
            _, cursor = _extract_braced(text, cursor)
        return text[start:cursor], cursor
    return None


def _split_added_content(content: str, macro: str) -> str:
    pieces: list[str] = []
    regular_start = 0
    cursor = 0
    depth = 0
    found = False
    while cursor < len(content):
        char = content[cursor]
        if char == "%" and not _is_escaped(content, cursor):
            newline = content.find("\n", cursor)
            cursor = len(content) if newline == -1 else newline + 1
            continue
        if char == "{" and not _is_escaped(content, cursor):
            depth += 1
            cursor += 1
            continue
        if char == "}" and not _is_escaped(content, cursor):
            depth = max(0, depth - 1)
            cursor += 1
            continue
        if depth == 0 and char == "\\":
            parsed = _parse_provenance_command(content, cursor)
            if parsed is not None:
                special, end = parsed
                ordinary = content[regular_start:cursor]
                if ordinary:
                    pieces.append(
                        ordinary if ordinary.isspace() else f"{macro}{{{ordinary}}}"
                    )
                pieces.append(special)
                found = True
                cursor = end
                regular_start = end
                continue
        cursor += 1
    if not found:
        return f"{macro}{{{content}}}"
    ordinary = content[regular_start:]
    if ordinary:
        pieces.append(ordinary if ordinary.isspace() else f"{macro}{{{ordinary}}}")
    return "".join(pieces)


def _denest_provenance(text: str) -> str:
    macros = (r"\DIFaddFL", r"\DIFadd")
    output: list[str] = []
    cursor = 0
    while cursor < len(text):
        candidates = [(text.find(f"{macro}{{", cursor), macro) for macro in macros]
        matches = [item for item in candidates if item[0] != -1]
        if not matches:
            output.append(text[cursor:])
            break
        index, macro = min(matches, key=lambda item: item[0])
        output.append(text[cursor:index])
        content, end = _extract_braced(text, index + len(macro))
        output.append(_split_added_content(content, macro))
        cursor = end
    result = "".join(output)
    for macro in macros:
        cursor = 0
        while True:
            index = result.find(f"{macro}{{", cursor)
            if index < 0:
                break
            content, end = _extract_braced(result, index + len(macro))
            if r"\review" in content or r"\selfadd" in content:
                raise WorkflowError(
                    "Could not safely separate provenance markup from latexdiff output."
                )
            cursor = end
    return result


def _parse_registry(path: Path) -> list[tuple[str, int]]:
    if not path.exists():
        raise WorkflowError(f"Marked build did not create a review registry: {path}")
    records: list[tuple[str, int]] = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw.strip():
            continue
        fields = raw.strip().split("|")
        if len(fields) != 2 or not fields[1].isdigit():
            raise WorkflowError(f"Malformed review registry at line {number}: {raw}")
        records.append((fields[0], int(fields[1])))
    return records


def _parse_labels(path: Path) -> dict[tuple[int, str], int]:
    if not path.exists():
        raise WorkflowError(
            f"Marked build did not create a line-number AUX file: {path}"
        )
    labels: dict[tuple[int, str], int] = {}
    text = path.read_text(encoding="utf-8", errors="replace")
    for block, edge, line in LABEL_PATTERN.findall(text):
        labels[(int(block), edge)] = int(line)
    return labels


def _format_location(start: int, end: int) -> str:
    return f"Line {start}" if start == end else f"Lines {start}--{end}"


def _join_locations(locations: list[str]) -> str:
    if not locations:
        return "Location unavailable"
    if len(locations) == 1:
        return locations[0]
    if len(locations) == 2:
        return f"{locations[0]} and {locations[1]}"
    return f"{', '.join(locations[:-1])}, and {locations[-1]}"


def _calculate_locations(build_dir: Path) -> dict[str, str]:
    registry = _parse_registry(build_dir / "manuscript_marked.reviewloc")
    labels = _parse_labels(build_dir / "manuscript_marked.aux")
    by_comment: dict[str, list[str]] = collections.defaultdict(list)
    for ids, block in registry:
        start = labels.get((block, "start"))
        end = labels.get((block, "end"))
        if start is None or end is None:
            raise WorkflowError(f"Line labels are missing for reviewer block {block}.")
        location = _format_location(start, end)
        for review_id in (item.strip() for item in ids.split(",")):
            if not REVIEW_ID.fullmatch(review_id):
                raise WorkflowError(
                    f"Invalid reviewer ID {review_id!r}; expected form 1-1."
                )
            if location not in by_comment[review_id]:
                by_comment[review_id].append(location)
    return {key: _join_locations(value) for key, value in by_comment.items()}


def build_marked_manuscript(
    config: ProjectConfig,
    round_number: int,
    run_dir: Path,
    engine_override: str | None = None,
) -> MarkedResult:
    """Build an R(N-1)-to-RN marked PDF and calculate temporary line locations."""
    if round_number < 1:
        raise WorkflowError("R0 has no marked manuscript; build its clean PDF instead.")
    previous = config.round_dir(round_number - 1)
    current = config.round_dir(round_number)
    if not previous.is_dir() or not current.is_dir():
        raise WorkflowError(
            f"Revision requires both r{round_number - 1} and r{round_number}."
        )
    if shutil.which("latexdiff") is None:
        raise WorkflowError("latexdiff is required for marked manuscripts.")
    if shutil.which("pdftotext") is None:
        raise WorkflowError("pdftotext is required for revision location extraction.")

    source_dir = run_dir / "marked_source"
    build_dir = run_dir / "marked_build"
    source_dir.mkdir(parents=True)
    roots = (previous, current, config.project)
    old_text = strip_provenance_wrappers(
        _flatten_tex(previous / "manuscript.tex", roots)
    )
    new_text = _flatten_tex(current / "manuscript.tex", roots)
    for bibliography_path in (
        "../../references/references",
        "../references/references",
        "references/references",
    ):
        old_text = old_text.replace(bibliography_path, "references")
        new_text = new_text.replace(bibliography_path, "references")
    publisher_path = f"../references/journal_template/{config.metadata.publisher}/"
    old_text = old_text.replace(publisher_path, "")
    new_text = new_text.replace(publisher_path, "")
    old_source = source_dir / "old.tex"
    new_source = source_dir / "new.tex"
    old_source.write_text(old_text, encoding="utf-8")
    new_source.write_text(new_text, encoding="utf-8")
    style = source_dir / "revision_preamble.tex"
    user_style = (config.references / "revision_style.tex").read_text(encoding="utf-8")
    style.write_text(f"{user_style}\n{REVISION_RUNTIME}", encoding="utf-8")
    _copy_resources(config, current, source_dir)

    command = [
        shutil.which("latexdiff") or "latexdiff",
        "--encoding=utf8",
        "--packages=none",
        f"--preamble={style}",
        "--disable-citation-markup",
        "--ignore-warnings",
        str(old_source),
        str(new_source),
    ]
    result = run_command(command, cwd=source_dir)
    marked_source = source_dir / "manuscript_marked.tex"
    marked_source.write_text(_denest_provenance(result.stdout), encoding="utf-8")
    compiled = compile_tex(
        marked_source,
        build_dir,
        config,
        engine_override,
        keep_intermediates=True,
    )
    extracted_text = run_dir / "marked_manuscript.txt"
    run_command(
        [
            shutil.which("pdftotext") or "pdftotext",
            str(compiled.pdf),
            str(extracted_text),
        ],
        cwd=run_dir,
    )
    if not extracted_text.exists() or extracted_text.stat().st_size == 0:
        raise WorkflowError("Marked PDF text extraction produced no text.")

    locations = _calculate_locations(build_dir)
    output = current / "output" / "manuscript_marked.pdf"
    output.parent.mkdir(exist_ok=True)
    shutil.copy2(compiled.pdf, output)
    return MarkedResult(pdf=output, locations=locations)
